noColor = false
logLevel = "debug"
cacheDirPath = "$HOME/.cache/dstm"

steamRootPath = "$HOME/Steam"
serverRootPath = "$HOME/DST/Server"
dataRootPath = "$HOME/DST/Klei"
worldsDirName = "Worlds"

separator = "-"
